# Generated by Django 5.2.17 on 2026-09-25 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('case_type', models.CharField(choices=[('work_permit', 'Work Permit'), ('study_permit', 'Study Permit')], max_length=40)),
                ('applicant_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ready_for_submission', 'Ready For Submission'), ('closed', 'Closed')], default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=10)),
                ('actor_label', models.CharField(blank=True, max_length=100)),
                ('event', models.CharField(max_length=60)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='cases.case')),
            ],
            options={
                'verbose_name_plural': 'audit log entries',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider', models.CharField(max_length=40)),
                ('result', models.JSONField(blank=True, null=True)),
                ('traces', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('text', models.TextField(help_text='Extracted plain text; the demo accepts UTF-8 text files only.')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=40)),
                ('extraction', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequirementChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('accepted_document_types', models.JSONField(default=list)),
                ('rules', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('satisfied', 'Satisfied')], default='open', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='cases.case')),
                ('satisfied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cases.casedocument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProposedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('accept_document', 'accept_document'), ('reject_document', 'reject_document'), ('mark_requirement_satisfied', 'mark_requirement_satisfied'), ('request_document', 'request_document'), ('flag_for_review', 'flag_for_review'), ('change_case_status', 'change_case_status')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=20)),
                ('rationale', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_actions', to='cases.agentrun')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_actions', to='cases.case')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_actions', to='cases.casedocument')),
                ('target_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cases.requirementchecklistitem')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('case',), name='one_active_run_per_case'),
        ),
        migrations.AddConstraint(
            model_name='requirementchecklistitem',
            constraint=models.UniqueConstraint(fields=('case', 'code'), name='unique_requirement_per_case'),
        ),
        migrations.AddIndex(
            model_name='proposedaction',
            index=models.Index(fields=['case', 'status'], name='cases_propo_case_id_5d25f8_idx'),
        ),
    ]
